import arcpy

sgCodeDescriptions = {"3.01.15.001": "Glacier Ice or Snowpack: snowpacks",
                      "3.01.15.002": "Glacier Ice or Snowpack: Glacier-icefield-icecap",
                      "3.01.14.715": "Anthropogenic deposits: undifferentiated",
                      "3.01.02.011": "Organic deposits: fen",
                      "3.01.02.013": "Organic deposits: bog",
                      "3.01.02.015": "Organic deposits: salt marsh",
                      "3.01.02.023": "Organic deposits: veneer",
                      "3.01.02.025": "Organic deposits: blanket",
                      "3.01.02.012": "Organic deposits: undifferentiated",
                      "3.01.03.295": "Eolian sediments: loess",
                      "3.01.03.299": "Eolian sediments: dunes",
                      "3.01.03.292": "Eolian sediments: veneer",
                      "3.01.03.297": "Eolian sediments: undifferentiated",
                      "3.01.01.107": "Colluvial and Mass-wasting deposits",
                      "3.01.01.097": "Colluvial and Mass-wasting deposits: apron or talus scree",
                      "3.01.01.155": "Colluvial and Mass-wasting deposits: landslide",
                      "3.01.01.139": "Colluvial and Mass-wasting deposits: rock-glacier",
                      "3.01.01.092": "Colluvial and Mass-wasting deposits: veneer",
                      "3.01.01.095": "Colluvial and Mass-wasting deposits: blanket",
                      "3.01.01.152": "Colluvial and Mass-wasting deposits: undifferentiated",
                      "3.01.04.265": "Alluvial sediments: floodplain",
                      "3.01.04.257": "Alluvial sediments: fan",
                      "3.01.04.255": "Alluvial sediments: intertidal or estuarine",
                      "3.01.04.269": "Alluvial sediments: terraced",
                      "3.01.04.252": "Alluvial sediments: veneer",
                      "3.01.04.267": "Alluvial sediments: blanket",
                      "3.01.04.263": "Alluvial sediments: undifferentiated",
                      "3.01.05.582": "Lacustrine sediments: beach",
                      "3.01.05.585": "Lacustrine sediments: deltaic",
                      "3.01.05.573": "Lacustrine sediments: littoral and nearshore",
                      "3.01.05.577": "Lacustrine sediments: offshore",
                      "3.01.05.572": "Lacustrine sediments: veneer",
                      "3.01.05.575": "Lacustrine sediments: blanket",
                      "3.01.05.583": "Lacustrine sediments: undifferentiated",
                      "3.01.06.495": "Marine sediments: terraced",
                      "3.01.06.497": "Marine sediments: beach",
                      "3.01.06.507": "Marine sediments: deltaic",
                      "3.01.06.492": "Marine sediments: intertidal",
                      "3.01.06.493": "Marine sediments: littoral and nearshore",
                      "3.01.06.509": "Marine sediments: offshore",
                      "3.01.06.502": "Marine sediments: veneer",
                      "3.01.06.505": "Marine sediments: blanket",
                      "3.01.06.503": "Marine sediments: undifferentiated",
                      "3.01.09.487": "Glaciomarine sediments: beach",
                      "3.01.09.525": "Glaciomarine sediments: deltaic",
                      "3.01.09.512": "Glaciomarine sediments: intertidal",
                      "3.01.09.513": "Glaciomarine sediments: littoral and nearshore",
                      "3.01.09.519": "Glaciomarine sediments: offshore",
                      "3.01.09.527": "Glaciomarine sediments: submarine outwash fan",
                      "3.01.09.517": "Glaciomarine sediments: submarine moraine",
                      "3.01.09.483": "Glaciomarine sediments: veneer",
                      "3.01.09.485": "Glaciomarine sediments: blanket",
                      "3.01.09.515": "Glaciomarine sediments: undifferentiated",
                      "3.01.08.645": "Glaciolacustrine sediments: beach",
                      "3.01.08.613": "Glaciolacustrine sediments: deltaic",
                      "3.01.08.612": "Glaciolacustrine sediments: littoral and nearshore",
                      "3.01.08.637": "Glaciolacustrine sediments: offshore",
                      "3.01.08.615": "Glaciolacustrine sediments: subaqueous outwash fan",
                      "3.01.08.617": "Glaciolacustrine sediments: subaqueous moraine",
                      "3.01.08.635": "Glaciolacustrine sediments: hummocky",
                      "3.01.08.642": "Glaciolacustrine sediments: veneer",
                      "3.01.08.647": "Glaciolacustrine sediments: blanket",
                      "3.01.08.643": "Glaciolacustrine sediments: undifferentiated",
                      "3.01.07.249": "Glaciofluvial sediments: outwash plain",
                      "3.01.07.237": "Glaciofluvial sediments: terraced",
                      "3.01.07.225": "Glaciofluvial sediments: outwash fan",
                      "3.01.07.215": "Glaciofluvial sediments: hummocky",
                      "3.01.07.217": "Glaciofluvial sediments: ice-contact",
                      "3.01.07.219": "Glaciofluvial sediments: kame terrace",
                      "3.01.07.229": "Glaciofluvial sediments: esker",
                      "3.01.07.223": "Glaciofluvial sediments: veneer",
                      "3.01.07.247": "Glaciofluvial sediments: blanket",
                      "3.01.07.235": "Glaciofluvial sediments: undifferentiated",
                      "3.01.10.357": "Glacial sediments: rock-glacierized moraine",
                      "3.01.10.375": "Glacial sediments: hummocky till",
                      "3.01.10.377": "Glacial sediments: moraine complex",
                      "3.01.10.385": "Glacial sediments: ridged till, moraine",
                      "3.01.10.387": "Glacial sediments: streamlined till",
                      "3.01.10.439": "Glacial sediments: till plain",
                      "3.01.10.057": "Glacial sediments: weathered till",
                      "3.01.10.355": "Glacial sediments: veneer",
                      "3.01.10.359": "Glacial sediments: blanket",
                      "3.01.10.373": "Glacial sediments: undifferentiated",
                      "3.01.11.175": "Weathered bedrock or regolith: veneer",
                      "3.01.11.169": "Weathered bedrock or regolith: blanket",
                      "3.01.11.177": "Weathered bedrock or regolith: undifferentiated",
                      "3.01.16.705": "Volcanic deposits: pyroclastic sediments",
                      "3.01.16.707": "Volcanic deposits: undifferentiated",
                      "3.01.12.082": "Undifferentiated deposits: undifferentiated",
                      "3.01.13.192": "Bedrock: sedimentary",
                      "3.01.13.187": "Bedrock: igneous",
                      "3.01.13.183": "Bedrock: metamorphic",
                      "3.01.13.185": "Bedrock: undifferentiated",
                      "2.01.01.008": "Unmapped Area"}


def main():
    sgLayerName = arcpy.GetParameterAsText(0)
    aprx = arcpy.mp.ArcGISProject('CURRENT')
    mapProject = aprx.listMaps(aprx.activeMap.name)[0]
    sgLayer = mapProject.listLayers(sgLayerName)[0]
    lyrCim = sgLayer.getDefinition('V2')
    for group in lyrCim.renderer.groups:
        for cls in group.classes:
            label = cls.label
            cls.label = sgCodeDescriptions[label]
    sgLayer.setDefinition(lyrCim)
    return


if __name__ == '__main__':
    main()